version: '3.3'

networks:
  monitor-net:
    driver: bridge

services:
  ecs-discovery:
    image: tkgregory/prometheus-ecs-discovery
    volumes:
      - ./output:/output
    environment:
      - AWS_REGION=$AWS_REGION
    command:
      - '--config.write-to=/output/ecs_file_sd.yml'
      - '--config.cluster=$AWS_CLUSTER'
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - ./output:/output
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: unless-stopped
    ports:
      - "9090:9090"
    expose:
      - 9090
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      - monitor-net